### ISSUE TITLE
snapshot.name causes compile issues

### ISSUE THREAD

**Issue by rowrow** [firebase/ios-drawing#1]
Love this sample project, thanks for it!

I think the 3 places where `snapshot.name` or `pathRef.name` appears cause compile issues. I don't remember if FB used to have such a property, but perhaps they just renamed it to something else?

**Comment by davideast** [comment]
It used to be `snapshot.name`, but now it's `snapshot.key`.

Would you like to send a PR?

**Comment by ramakula** [comment]
I did.
